Issue/#91 re-structure tests
amaembo/streamex pull request #224
Opened 2020-06-19 22:07 UTC by dma1979

#### Final results: **471** tests = **393** API tests + **78** internal tests

#### Some additional points:
1) Currently latest JUnit 4 Generation is used - 4.12 .
What do you think about using 5G(jupiter)?
It will allow to use more functional approach(lambdas) even for testing itself. Ane even more: extensions, conditions, parameterized tests, dynamic tests and etc.

2) What if we apply grouping: categories in JUnit 4G or tags in JUnit 5G?
F.e. we can split all test to 2 categories/tags: 
- api
- internal

From the [documentation](https://junit.org/junit5/docs/5.4.2/api/org/junit/jupiter/api/Tag.html) :
tags are used to filter which tests are executed for a given test plan. For example, a development team may tag tests with values such as "fast", "slow", "ci-server", etc. and then supply a list of tags to be used for the current test plan, potentially dependent on the current environment.

2020-08-02 02:08 UTC, amaembo commented
Please resolve conflicts.

2020-08-04 21:31 UTC, dma1979 commented
Final improvements for StreamEx tests: 
- 477 tests were split to 2 categories
  -  399 API tests 
   - 78 internal tests
 - native junit assertThrows(since 4.13) is used

2020-08-13 16:38 UTC, dma1979 commented
Tagir, could you please give your feedback?

2020-08-30 15:44 UTC, amaembo requested changes
Seems some qualifiers were added due to move refactoring...

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/DoubleCollectorTest.java
> +        Assert.assertEquals(7.0, DoubleStreamEx.of(1.0, 2.0, 3.5).collect(DoubleCollector.reducing(1.0, (a, b) -> a * b)), 0.0);
Why explicit `Assert.` qualifier was added here?

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/DoubleCollectorTest.java
> +        Assert.assertArrayEquals(LongStreamEx.of(1, 1, 2, 3).toArray(), DoubleStreamEx.of(0.8, 1.3, 1.7, 2.9).collect(
Same

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/DoubleStreamExTest.java
> +        Assert.assertEquals(6, IntStreamEx.range(0, 4).asDoubleStream().sum(), 0);
Same.

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/EmitterTest.java
> +        TestHelpers.checkSpliterator("flatTest", asList(4, 4, 4, 4, 3, 3, 3, 2, 2, 1),
Explicit `TestHelpers.` qualifiers.

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/EntryStreamTest.java
> -        assertEquals(0, EntryStream.empty().count());
The duplication here was intentional and it actually caught a bug in the early version of StreamEx when `EntryStream.emtpy()` returned a shared object. Please restore it.

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/IntCollectorTest.java
> +        Assert.assertEquals(expected, IntStreamEx.range(10000).collect(IntCollector.joining(", ")));
Explicit qualifier.

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/IntCollectorTest.java
> +        Assert.assertArrayEquals(IntStreamEx.range(1000).asDoubleStream().toArray(), IntStreamEx.range(1000).collect(
Same

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/IntStreamExTest.java
> +        Assert.assertArrayEquals(new int[] {}, IntStreamEx.empty().toArray());
Same

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/LongStreamExTest.java
> +        Assert.assertArrayEquals(new long[] {}, LongStreamEx.empty().toArray());
Explicit qualifier

2020-08-30 15:44 UTC, amaembo commented on src/test/java/one/util/streamex/api/LongStreamExTest.java
> +        Assert.assertEquals(0L, IntStreamEx.empty().intersperse(1).count());
Same

2020-09-06 08:39 UTC, merged